- label: Project
  nodes:
    - label: Project
      gid: "project:{{name}}"
      merge: true
      filter:
        - hasMember
  edges:
    - index: hasMember
      fromLabel: Project
      label: hasMember
      toLabel: Individual
      from: "project:{{name}}"
      to: "{{_index}}"

- label: Individual
  nodes:
    - label: Individual
      gid: "individual:{{datasetId}}:{{name}}"
      merge: true
      splice:
        - info

- label: Cohort
  nodes:
    - label: Cohort
      gid: "cohort:{{name}}"
      merge: true
      filter:
        - hasMember
  edges:
    - index: hasMember
      fromLabel: Cohort
      label: hasSample
      toLabel: Biosample
      from: "cohort:{{name}}"
      to: "{{_index}}"

- label: Biosample
  nodes:
    - label: Biosample
      gid: "biosample:{{datasetId}}:{{name}}"
      merge: true
      filter:
        - disease
      splice:
        - info
    - label: OntologyTerm
      gid: "term:{{disease.term}}"
      splice:
        - disease
  edges:
    - fromLabel: Biosample
      label: sampleOf
      toLabel: Individual
      from: "biosample:{{datasetId}}:{{name}}"
      to: "{{individualId}}"
    - fromLabel: Biosample
      label: hasDisease
      toLabel: OntologyTerm
      from: "biosample:{{datasetId}}:{{name}}"
      to: "term:{{disease.term}}"
  embedded:
    - label: OntologyTerm
      path: disease

- label: CallSet
  edges:
    - fromLabel: Variant
      label: variantFor
      toLabel: Biosample
      to: "{{biosampleId}}"
      lookup: "callSet:{{name}}"

- label: Variant
  nodes:
    - label: Variant
      gid: "variant:{{referenceName}}:{{start}}:{{end}}:{{referenceBases}}:{{alternateBases|join:,}}"
      merge: true
      filter:
        - calls
      splice:
        - info
      properties:
        alternateBases: "{{alternateBases|join:,}}"
  edges:
    - index: calls
      fromLabel: Variant
      label: variantFor
      toLabel: Biosample
      from: "variant:{{referenceName}}:{{start}}:{{end}}:{{referenceBases}}:{{alternateBases|join:,}}"
      lookup: "{{_index.callSetId}}"

- label: VariantAnnotation
  edges:
    - index: transcriptEffects
      fromLabel: Variant
      label: variantIn
      toLabel: Gene
      from: "{{variantId}}"
      to: "{{_index.featureId}}"
      properties:
        effects: "{{_index.effects|each:term|join:,}}"

- label: ResponseCurve
  edges:
    - fromLabel: Biosample
      label: responseTo
      toLabel: Compound
      from: "{{sample}}"
      to: "{{compound}}"
      merge: true

- label: Compound
  nodes:
    - label: Compound
      gid: "compound:{{name}}"
      merge: true
      filter:
        - synonyms
  edges:
    - fromLabel: Compound
      label: targetsGene
      toLabel: Gene
      from: "compound:{{name}}"
      to: "{{target}}"
    - index: synonyms
      fromLabel: Compound
      label: sameAs
      toLabel: Compound
      from: "{{_index}}"
      to: "compound:{{name}}"

- label: Gene
  nodes:
    - label: Gene
      gid: "gene:{{symbol}}"
      merge: true
      filter:
        - inFamily
        - citedFrom
  edges:
    - index: citedFrom
      fromLabel: Gene
      label: citedFrom
      toLabel: Pubmed
      from: "gene:{{symbol}}"
      to: "{{_index}}"
    - index: inFamily
      fromLabel: Gene
      label: inFamily
      toLabel: GeneFamily
      from: "gene:{{symbol}}"
      to: "{{_index}}"

- label: GeneSynonym
  edges:
    - index: inDatabase
      fromLabel: GeneDatabase
      label: synonymFor
      toLabel: Gene
      from: "{{_index}}"
      to: "{{synonymFor|first}}"
      splice:
        - info

- label: GeneDatabase
  nodes:
    - label: GeneDatabase
      gid: "geneDatabase:{{name}}"
      merge: true

- label: GeneFamily
  nodes:
    - label: GeneFamily
      gid: "geneFamily:{{tag}}"
      merge: true

- label: GeneExpression
  nodes:
    - label: GeneExpression
      gid: "geneExpression:{{biosampleId}}"
      merge: true
  edges:
    - fromLabel: GeneExpression
      label: expressionFor
      toLabel: Biosample
      from: "geneExpression:{{biosampleId}}"
      to: "{{biosampleId}}"

- label: Pubmed
  nodes:
    - label: Pubmed
      gid: "pubmed:{{pmid}}"
      merge: true

- label: CNACallSet
  edges:
    - fromLabel: CNASegment
      label: segmentOf
      toLabel: Biosample
      to: "{{bioSampleId}}"
      lookup: "cnaCallSet:{{bioSampleId}}"
      
- label: CNASegment
  nodes:
    - label: CNASegment
      gid: "cnaSegment:{{callSetId}}:{{referenceName}}:{{start}}:{{end}}:{{value}}"
      merge: true
      filter:
        - genes
  edges:
    - fromLabel: CNASegment
      label: segmentOf
      toLabel: Biosample
      from: "cnaSegment:{{callSetId}}:{{referenceName}}:{{start}}:{{end}}:{{value}}"
      lookup: "{{callSetId}}"
    - index: genes
      fromLabel: CNASegment
      label: segmentIn
      toLabel: Gene
      from: "cnaSegment:{{callSetId}}:{{referenceName}}:{{start}}:{{end}}:{{value}}"
      to: "{{_index}}"

- label: Evidence
  nodes:
    - label: Evidence
      gid: "evidence:{{genes|sort|join:,}}:{{association.phenotype.description}}"
      properties:
        source: "{{source}}"
        genotype: "{{genes|sort|join:,}}"
        phenotype: "{{association.phenotype.description}}"
    - label: OntologyTerm
      gid: "term:{{association.phenotype.description}}"
      properties:
        term: "{{association.phenotype.description}}"
  edges:
    - index: features
      fromLabel: Evidence
      label: genotype
      toLabel: Gene
      from: "evidence:{{genes|sort|join:,}}:{{association.phenotype.description}}"
      to: "gene:{{_index.geneSymbol}}"
      splice:
        - _index
    - index: association.environmentalContexts
      fromLabel: Evidence
      label: environmentalContext
      toLabel: Compound
      from: "evidence:{{genes|sort|join:,}}:{{association.phenotype.description}}"
      to: "{{_index.id}}"
      properties:
        response: "{{association.response_type}}"
    - index: association.evidence.0.info.publications
      fromLabel: Evidence
      label: evidence
      toLabel: Pubmed
      from: "evidence:{{genes|sort|join:,}}:{{association.phenotype.description}}"
      to: "pubmed:{{_index|flatten|split:/|last}}"
    - fromLabel: Evidence
      label: phenotype
      toLabel: OntologyTerm
      from: "evidence:{{genes|sort|join:,}}:{{association.phenotype.description}}"
      to: "term:{{association.phenotype.description}}"
      
      
